#!/bin/sh

# PROVIDE: samlet-chat
# REQUIRE: LOGIN postgresql
# KEYWORD: shutdown

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

. /etc/rc.subr

desc="samlet-chat daemon"
name=samlet-chat
rcvar=chat_enable

load_rc_config $name

: ${chat_enable:=NO}

chat_env="SAMLETCHAT_ORIGIN=https://samlet-chat.example.com \
SAMLETCHAT_PORT=8080 \
SAMLETCHAT_POSTGRES=postgres://samlet-chat:samlet-chat@db:5432/samlet-chat?sslmode=disable \
SAMLETCHAT_STATIC=/usr/local/share/samlet-chat"
chat_user=www

command="/usr/local/bin/samlet-chat"
command_args=" >> /var/log/samlet-chat/${name}.log 2>&1 &"

run_rc_command "$1"
